package UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import MODEL.SoundPlayer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class HomeFrame extends javax.swing.JFrame {

    private SoundPlayer musicPlayer;
    private boolean isPlaying = true;
    private ImageIcon playIcon = new ImageIcon("src/minesweeper/img/play_11zon.png");
    private ImageIcon pauseIcon = new ImageIcon("src/minesweeper/img/pause_11zon.png");

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        musicPlayer = new SoundPlayer();
        musicPlayer = SoundPlayer.getInstance();
        musicPlayer.playMusic("src/UI/Music/ThienLyOi-JackJ97-13829746.wav");
        btnStopPlay.setIcon(pauseIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPLay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSetting = new javax.swing.JLabel();
        btnBXH = new javax.swing.JButton();
        btnStopPlay = new javax.swing.JToggleButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông Lý Như Hầu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPLay.setBackground(new java.awt.Color(0, 153, 153));
        btnPLay.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        btnPLay.setText("Play");
        btnPLay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPLay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 190, 50));

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 190, 50));

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/img/setting_11zon.png"))); // NOI18N
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 40));

        btnBXH.setBackground(new java.awt.Color(0, 153, 153));
        btnBXH.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        btnBXH.setText("BXH");
        btnBXH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBXHActionPerformed(evt);
            }
        });
        getContentPane().add(btnBXH, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 190, 50));

        btnStopPlay.setBackground(new java.awt.Color(0, 153, 153));
        btnStopPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/img/pause_11zon.png"))); // NOI18N
        btnStopPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnStopPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 50, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/img/MS_Thumbnail.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPLayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLayActionPerformed
        Minesweeper gameForm = new Minesweeper();
        // Hiển thị form Minesweeper
        gameForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPLayActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát không?",
                "Xác nhận thoát",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBXHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBXHActionPerformed
        BangXepHang gameForm = new BangXepHang();
        gameForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBXHActionPerformed

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked

    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnStopPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopPlayActionPerformed
        if (musicPlayer.isPlaying()) {
            musicPlayer.stopMusic();
            isPlaying = false;
            btnStopPlay.setIcon(playIcon);
        } else {
            musicPlayer.playMusic("src/UI/Music/ThienLyOi-JackJ97-13829746.wav");
            isPlaying = true;
            btnStopPlay.setIcon(pauseIcon);
        }

    }//GEN-LAST:event_btnStopPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnBXH;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPLay;
    private javax.swing.JLabel btnSetting;
    private javax.swing.JToggleButton btnStopPlay;
    // End of variables declaration//GEN-END:variables
}
